### PR TITLE
Add QSIPrep 0.14.2

### LINKED ISSUE #60: add qsiprep image
We have a stable version 0.14.2, I'd be happy to add this here. The Docker image is at pennbbl/qsiprep:0.14.2

### PR DESCRIPTION
**Pull request by mattcieslak**
Adds QSIPrep 0.14.2, closes #60

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh, thank you ! I wish it was this simple... due to singularity-hub going readonly and we are hosting only older images, I need to adjust my mighty bash prototype script to also build those images "locally" instead of relying to singularity-hub -- I am hosting/providing them all (including singularity-hub archive) anyways from datasets.datalad.org... will try to accomplish that tune up today.

"good news" is that qsiprep 0.14.2 listed on http://bids-apps.neuroimaging.io/apps/ so the script should automagically handle it and no such PR would be needed

**Comment by mattcieslak** [comment]
Ok, this is very good to know! We're also using fmriprep 20.2.3, will your next run also add that image?

**Comment by yarikoptic** [comment]
both should be in, please check if usable ;-)

**Comment by yarikoptic** [comment]
FWIW -- all bids-apps updated, and job is now a cron job so they should stay updated ;-) let's see how that goes

**Pull request closed without merging**
