### PR TITLE
Switch from Travis to GitHub Actions

### LINKED ISSUE #98: Move from travis to github actions
I believe travis is defunct.  Let's move the tests in .travis.yml into a github action (also replace badge in README.md)

### PR DESCRIPTION
**Pull request by jwodder**
Closes #98.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic The tests are failing on macOS because the dummy Docker script isn't being passed the arguments it expects during the script tests.  Instead of a command line ending with:

```
--pwd /singularity 'foo bar' blah 45.5 /dir 'bar;' 'foo&' '\${foo}'
```

it's getting:

```
--pwd '/tmp/tmp dir.XXXXXX.cieII6oF' /Users/runner/work/containers/containers/scripts/tests/arg-test.simg sh -c 'find /tmp /var/tmp && cat "/tmp/tmp dir.XXXXXX.cieII6oF/file"'
```

Also, shellcheck is printing out a bunch of messages, but it's still exiting 0, so no one will ever check to see them.

**Comment by jwodder** [comment]
@yarikoptic I've fixed the shellcheck issue, though I had to skip checking of `scripts/utils/get-rid-of-datalad-remote.sh`, which is a zsh script, which shellcheck does not support.

**Comment by yarikoptic** [comment]
Awesome, thank you! And that script was one truck pony anyways

**Comment by yarikoptic** [comment]
ok, one problem as identified by tests

```
line 130: mapfile: command not found
```
happening on OSX, according to https://github.com/jitterbit/get-changed-files/issues/15#issuecomment-724909010 :+1: 

> The problem is that macOS has bash 3 and mapfile was introduced in bash 4.
> I found a solution, add this step in front in your workflow:

    - if: contains( matrix.os, 'macos')
      name: Install bash 5.0 under macOS for mapfile
      run: |
        brew install bash
        sudo mv /usr/local/bin/bash /bin/bash


but I would like to avoid that since then OSX folks might be left behind... will think about it...

**Comment by jwodder** [comment]
@yarikoptic The `mapfile` thing is addressed by #105.  The remaining, bigger problem is still https://github.com/ReproNim/containers/pull/99#issuecomment-1563453156.

**Comment by yarikoptic** [comment]
rebased, force pushed.

**Comment by yarikoptic** [comment]
ok, green now (after we just started to skip here too ;) ) -- so let's merge and consider "DONE" ;)

**Pull request merged**
